// Generated by test/demo/demo.test.ts from ui/Pane.tsx over the fixture world.
// Do not edit: `RENDER_DEMO=1 pnpm vitest run test/demo` writes it again.

export type Segment = {
  readonly text: string
  readonly tone?: string
  readonly bold?: true
  readonly dim?: true
  readonly ring?: true
}
export type Frame = {
  readonly title: string
  readonly caption: string
  readonly lines: readonly (readonly Segment[])[]
}

export const COLUMNS = 62

export const FRAMES: readonly Frame[] = [
  {
    "title": "Installed",
    "caption": "Every mod, what it can do at a glance, and what changed.",
    "lines": [
      [
        {
          "text": "1: Installed  "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "5 mods · 5 on"
        }
      ],
      [
        {
          "text": "› "
        },
        {
          "text": "filter by name",
          "dim": true
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " broken                   "
        },
        {
          "dim": true,
          "text": "0.0.1"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "user"
        },
        {
          "text": "     "
        },
        {
          "tone": "error",
          "text": "▲1"
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " quiet-bash               "
        },
        {
          "dim": true,
          "text": "0.2.0"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "user"
        },
        {
          "text": "     "
        },
        {
          "tone": "claude",
          "text": "◆1"
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " redactor                 "
        },
        {
          "dim": true,
          "text": "2.1.0"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "project"
        },
        {
          "text": "  "
        },
        {
          "tone": "claude",
          "text": "◆3"
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " spawner                  "
        },
        {
          "dim": true,
          "text": "1.0.0"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "local"
        },
        {
          "text": "    "
        },
        {
          "tone": "claude",
          "text": "◆2"
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "turn-band"
        },
        {
          "text": "                "
        },
        {
          "dim": true,
          "text": "0.4.0"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "user"
        },
        {
          "text": "     "
        },
        {
          "tone": "claude",
          "text": "◆2"
        },
        {
          "text": " "
        },
        {
          "tone": "warning",
          "text": "new"
        }
      ],
      [
        {
          "text": "e: toggle  x: remove  z: undo  r: refresh  f: filter  j: jobs"
        }
      ],
      [
        {
          "text": "h: help  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  },
  {
    "title": "Detail",
    "caption": "An update gave turn-band a new power: said before it surprises you.",
    "lines": [
      [
        {
          "text": "1: Installed  "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "5 mods · 5 on"
        }
      ],
      [
        {
          "bold": true,
          "text": "turn-band"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "0.4.0"
        }
      ],
      [
        {
          "tone": "success",
          "text": "● on"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "· user · fixtures"
        }
      ],
      [
        {
          "text": "e: disable  x: remove  c: copy id"
        }
      ],
      [
        {
          "dim": true,
          "text": "↑ runs from its marketplace folder: no updates"
        }
      ],
      [
        {
          "tone": "warning",
          "bold": true,
          "text": "New since 0.3.1"
        }
      ],
      [
        {
          "tone": "warning",
          "text": "◆"
        },
        {
          "text": " Can run programs or change files on your machine"
        }
      ],
      [
        {
          "bold": true,
          "text": "Notable"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "◆"
        },
        {
          "text": " Can change what the model reads"
        }
      ],
      [
        {
          "bold": true,
          "text": "What it can do"
        }
      ],
      [
        {
          "text": "Your machine "
        },
        {
          "dim": true,
          "text": "process.run"
        }
      ],
      [
        {
          "text": "What the model sees "
        },
        {
          "dim": true,
          "text": "prompt.submit"
        }
      ],
      [
        {
          "dim": true,
          "text": "Display only"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "turn.complete ui.render clock.now state.set ui.t"
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "text": "j: jobs  h: help  "
        },
        {
          "dim": true,
          "text": "esc back"
        }
      ]
    ]
  },
  {
    "title": "Discover",
    "caption": "Every marketplace, searchable, with the mods found in it.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "  2: Discover  "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "201 shown · "
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "text": "› "
        },
        {
          "text": "search the catalogue",
          "dim": true
        }
      ],
      [
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "frontend-design"
        },
        {
          "text": "            "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "1.2M"
        }
      ],
      [
        {
          "text": " code-review                "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "492k"
        }
      ],
      [
        {
          "text": " context7                   "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "458k"
        }
      ],
      [
        {
          "text": " security-guidance          "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "273k"
        }
      ],
      [
        {
          "text": " telegram                   "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "110k"
        }
      ],
      [
        {
          "text": " plugin-dev                 "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "73k"
        }
      ],
      [
        {
          "text": " agent-sdk-dev              "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "70k"
        }
      ],
      [
        {
          "text": " gopls-lsp                  "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "45k"
        }
      ],
      [
        {
          "text": " discord                    "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "36k"
        }
      ],
      [
        {
          "text": " php-lsp                    "
        },
        {
          "dim": true,
          "text": "claude-plugins-offi"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "?"
        },
        {
          "text": "      "
        },
        {
          "dim": true,
          "text": "35k"
        }
      ],
      [
        {
          "dim": true,
          "text": "1–10 of 201"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "g: first"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "b: last"
        }
      ],
      [
        {
          "text": "i: install  k: mods only  o: sort by name  m: add marketplace"
        }
      ],
      [
        {
          "text": "r: refresh  f: search  j: jobs  h: help  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  },
  {
    "title": "Review",
    "caption": "Nothing runs before you read what will run, and where.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "  2: Discover  "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "201 shown · "
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "bold": true,
          "text": "Install aws-serverless from claude-plugins-official"
        }
      ],
      [
        {
          "text": "y: confirm  n: cancel"
        }
      ],
      [
        {
          "text": "scope: "
        },
        {
          "text": "user: every project ▾",
          "tone": "claude"
        }
      ],
      [
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " install   "
        },
        {
          "bold": true,
          "text": "aws-serverless"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "claude-plugins-official · user"
        }
      ],
      [
        {
          "text": "modmgr reads what it can do once it is installed,"
        }
      ],
      [
        {
          "text": "and shows it in its detail then."
        }
      ],
      [
        {
          "text": "Takes effect after the reload modmgr runs."
        }
      ],
      [
        {
          "dim": true,
          "text": "Runs"
        }
      ],
      [
        {
          "dim": true,
          "text": "  claude plugin install aws-serverless@claude-plugins-officia"
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "dim": true,
          "text": "esc back"
        }
      ]
    ]
  },
  {
    "title": "Health",
    "caption": "What needs you, worst first, each with a one-key fix.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "  4: Health ▲2  "
        },
        {
          "dim": true,
          "text": "2 problems"
        }
      ],
      [
        {
          "tone": "error",
          "text": "▲"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "broken"
        },
        {
          "text": "            "
        },
        {
          "ring": true,
          "text": "validate finds 1 error in it"
        },
        {
          "text": "      "
        },
        {
          "tone": "claude",
          "text": "→ see it"
        }
      ],
      [
        {
          "tone": "error",
          "text": "▲"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "redactor"
        },
        {
          "text": "          1 failure while it reloaded; l… "
        },
        {
          "tone": "claude",
          "text": "→ validate"
        }
      ],
      [
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "modmgr"
        },
        {
          "text": "            5 enabled"
        }
      ],
      [
        {
          "text": "                   updates checked never, every … "
        },
        {
          "tone": "claude",
          "text": "→ check now"
        }
      ],
      [
        {
          "text": "                   detector: 50 of 200 checked, 0 mods found…"
        }
      ],
      [
        {
          "text": "                   cache: 194 B                       "
        },
        {
          "tone": "claude",
          "text": "→ clear"
        }
      ],
      [
        {
          "text": "                   A hook that fails is logge… "
        },
        {
          "tone": "claude",
          "text": "→ copy command"
        }
      ],
      [
        {
          "text": "l: reload  r: refresh  j: jobs  h: help  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  }
]
