// Generated by test/demo/demo.test.ts from ui/Pane.tsx over the fixture world.
// Do not edit: `RENDER_DEMO=1 pnpm vitest run test/demo` writes it again.

export type Segment = {
  readonly text: string
  readonly tone?: string
  readonly bold?: true
  readonly dim?: true
  readonly underline?: true
  readonly ring?: true
}
export type Frame = {
  readonly title: string
  readonly caption: string
  readonly lines: readonly (readonly Segment[])[]
}

export const COLUMNS = 96

export const FRAMES: readonly Frame[] = [
  {
    "title": "Installed",
    "caption": "Every mod, what it can do at a glance, and what changed.",
    "lines": [
      [
        {
          "tone": "claude",
          "bold": true,
          "underline": true,
          "text": "Installed"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "r: refresh"
        }
      ],
      [
        {
          "dim": true,
          "text": "5 of 5 mods on"
        }
      ],
      [
        {
          "dim": true,
          "text": "╭──────────────────────────────────────────────────────────────────────────────────────────────╮"
        }
      ],
      [
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "⌕ Filter 5 mods"
        },
        {
          "text": "                                                                    "
        },
        {
          "dim": true,
          "text": "f: filter"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "╰──────────────────────────────────────────────────────────────────────────────────────────────╯"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " broken             "
        },
        {
          "tone": "error",
          "text": "▲1"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "redactor"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "2.1.0"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " quiet-bash         "
        },
        {
          "tone": "claude",
          "text": "◆1"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "success",
          "text": "● on"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "· project · fixtures"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "❯"
        },
        {
          "text": " "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "redactor"
        },
        {
          "text": "           "
        },
        {
          "tone": "claude",
          "text": "◆3"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " e: disable  x: remove  c: copy id"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " spawner            "
        },
        {
          "tone": "claude",
          "text": "◆2"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "↑ runs from its marketplace folder: no updates"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " turn-band          "
        },
        {
          "tone": "claude",
          "text": "◆2"
        },
        {
          "text": " "
        },
        {
          "tone": "warning",
          "text": "new"
        },
        {
          "text": "          "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "Notable"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "claude",
          "text": "◆"
        },
        {
          "text": " Can read your conversation or files and send data out"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "claude",
          "text": "◆"
        },
        {
          "text": " Reads environment variables that look like secrets"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "claude",
          "text": "◆"
        },
        {
          "text": " Can change what the model reads"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "What it can do"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " Network "
        },
        {
          "dim": true,
          "text": "http.fetch"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " Session content "
        },
        {
          "dim": true,
          "text": "env.get session.messages"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " What the model sees "
        },
        {
          "dim": true,
          "text": "session.append"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "Display only"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "session.end"
        }
      ],
      [
        {
          "dim": true,
          "text": "────────────────────────────────────────────────────────────────────────────────────────────────"
        }
      ],
      [
        {
          "text": "z: undo                                                              "
        },
        {
          "dim": true,
          "text": "j: jobs"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "h: keys"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  },
  {
    "title": "Detail",
    "caption": "An update gave turn-band a new power: said before it surprises you.",
    "lines": [
      [
        {
          "tone": "claude",
          "bold": true,
          "underline": true,
          "text": "Installed"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        }
      ],
      [
        {
          "dim": true,
          "text": "5 of 5 mods on"
        }
      ],
      [
        {
          "dim": true,
          "text": "╭──────────────────────────────────────────────────────────────────────────────────────────────╮"
        }
      ],
      [
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "⌕ Filter 5 mods"
        },
        {
          "text": "                                                                    "
        },
        {
          "dim": true,
          "text": "f: filter"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "╰──────────────────────────────────────────────────────────────────────────────────────────────╯"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " broken             "
        },
        {
          "tone": "error",
          "text": "▲1"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "turn-band"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "0.4.0"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " quiet-bash         "
        },
        {
          "tone": "claude",
          "text": "◆1"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "success",
          "text": "● on"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "· user · fixtures"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " redactor           "
        },
        {
          "tone": "claude",
          "text": "◆3"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " e: disable  x: remove  c: copy id"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " spawner            "
        },
        {
          "tone": "claude",
          "text": "◆2"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "↑ runs from its marketplace folder: no updates"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "❯"
        },
        {
          "text": " "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "turn-band"
        },
        {
          "text": "          "
        },
        {
          "tone": "claude",
          "text": "◆2"
        },
        {
          "text": "              "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "warning",
          "bold": true,
          "text": "New since 0.3.1"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "warning",
          "text": "◆"
        },
        {
          "text": " Can run programs or change files on your machine"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "Notable"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "claude",
          "text": "◆"
        },
        {
          "text": " Can change what the model reads"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "What it can do"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " Your machine "
        },
        {
          "dim": true,
          "text": "process.run"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " What the model sees "
        },
        {
          "dim": true,
          "text": "prompt.submit"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "Display only"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "turn.complete ui.render clock.now state.s"
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "✓ validates"
        }
      ],
      [
        {
          "dim": true,
          "text": "────────────────────────────────────────────────────────────────────────────────────────────────"
        }
      ],
      [
        {
          "text": "                                                                      "
        },
        {
          "dim": true,
          "text": "j: jobs"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "h: keys"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "esc back"
        }
      ]
    ]
  },
  {
    "title": "Discover",
    "caption": "The mods in every marketplace you have, found at once.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "   "
        },
        {
          "tone": "claude",
          "bold": true,
          "underline": true,
          "text": "Discover"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        },
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "r: refresh"
        }
      ],
      [
        {
          "dim": true,
          "text": "5 mods"
        }
      ],
      [
        {
          "dim": true,
          "text": "╭──────────────────────────────────────────────────────────────────────────────────────────────╮"
        }
      ],
      [
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "⌕ Search 5 mods"
        },
        {
          "text": "                                                                    "
        },
        {
          "dim": true,
          "text": "f: search"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "╰──────────────────────────────────────────────────────────────────────────────────────────────╯"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "❯"
        },
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "secret-scrub"
        },
        {
          "text": "                    "
        },
        {
          "dim": true,
          "text": "4.2k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "secret-scrub"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "1.0.0"
        }
      ],
      [
        {
          "text": "  commit-guard                    "
        },
        {
          "dim": true,
          "text": "2.8k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "claude",
          "text": "◆ mod"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "· fixtures · 4.2k installs"
        }
      ],
      [
        {
          "text": "  turn-timer                      "
        },
        {
          "dim": true,
          "text": "1.9k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " i: install  c: copy id"
        }
      ],
      [
        {
          "text": "  cost-meter                      "
        },
        {
          "dim": true,
          "text": "1.2k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " Masks tokens and keys in tool output before the model"
        }
      ],
      [
        {
          "text": "  quiet-hours                      "
        },
        {
          "dim": true,
          "text": "610"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " reads it."
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "from github.com/modmgr-fixtures/secret-scrub"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "What it can do is read once it is installed."
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "────────────────────────────────────────────────────────────────────────────────────────────────"
        }
      ],
      [
        {
          "text": "o: sort by name  m: marketplace                                      "
        },
        {
          "dim": true,
          "text": "j: jobs"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "h: keys"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  },
  {
    "title": "Review",
    "caption": "Nothing runs before you read what will run, and where.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "   "
        },
        {
          "tone": "claude",
          "bold": true,
          "underline": true,
          "text": "Discover"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "4: Health ▲1"
        }
      ],
      [
        {
          "dim": true,
          "text": "5 mods"
        }
      ],
      [
        {
          "dim": true,
          "text": "╭──────────────────────────────────────────────────────────────────────────────────────────────╮"
        }
      ],
      [
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "⌕ Search 5 mods"
        },
        {
          "text": "                                                                    "
        },
        {
          "dim": true,
          "text": "f: search"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "╰──────────────────────────────────────────────────────────────────────────────────────────────╯"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "❯"
        },
        {
          "text": " "
        },
        {
          "ring": true,
          "text": "secret-scrub"
        },
        {
          "text": "                    "
        },
        {
          "dim": true,
          "text": "4.2k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "Install secret-scrub from fixtures"
        }
      ],
      [
        {
          "text": "  commit-guard                    "
        },
        {
          "dim": true,
          "text": "2.8k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " y: confirm  n: cancel"
        }
      ],
      [
        {
          "text": "  turn-timer                      "
        },
        {
          "dim": true,
          "text": "1.9k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " scope: "
        },
        {
          "text": "user: every project ▾",
          "tone": "claude"
        }
      ],
      [
        {
          "text": "  cost-meter                      "
        },
        {
          "dim": true,
          "text": "1.2k"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "tone": "success",
          "text": "●"
        },
        {
          "text": " install   "
        },
        {
          "bold": true,
          "text": "secret-scrub"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "1.0.0 · fixtures · user"
        }
      ],
      [
        {
          "text": "  quiet-hours                      "
        },
        {
          "dim": true,
          "text": "610"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " modmgr reads what it can do once it is installed,"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " and shows it in its detail then."
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " Takes effect after the reload modmgr runs."
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "Runs"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "dim": true,
          "text": "  claude plugin install secret-scrub@fixtures --scope "
        },
        {
          "text": "…"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "────────────────────────────────────────────────────────────────────────────────────────────────"
        }
      ],
      [
        {
          "text": "                                                                                        "
        },
        {
          "dim": true,
          "text": "esc back"
        }
      ]
    ]
  },
  {
    "title": "Health",
    "caption": "What needs you, worst first, each with a one-key fix.",
    "lines": [
      [
        {
          "dim": true,
          "text": "1: Installed"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "2: Discover"
        },
        {
          "text": "   "
        },
        {
          "dim": true,
          "text": "3: Dev"
        },
        {
          "text": "   "
        },
        {
          "tone": "claude",
          "bold": true,
          "underline": true,
          "text": "Health ▲2"
        },
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "r: refresh"
        }
      ],
      [
        {
          "dim": true,
          "text": "2 problems to look at"
        }
      ],
      [
        {
          "tone": "claude",
          "text": "❯"
        },
        {
          "text": " "
        },
        {
          "tone": "error",
          "text": "▲"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "broken"
        },
        {
          "text": "     "
        },
        {
          "ring": true,
          "text": "validate finds 1 error"
        },
        {
          "text": "… "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "broken"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "error",
          "text": "▲"
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "redactor"
        },
        {
          "text": "   1 failure while it rel… "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " validate finds 1 error in it"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "subtle",
          "text": " "
        },
        {
          "text": " "
        },
        {
          "bold": true,
          "text": "modmgr"
        },
        {
          "text": "     5 enabled               "
        },
        {
          "dim": true,
          "text": "│"
        },
        {
          "text": " → see it"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "subtle",
          "text": " "
        },
        {
          "text": "            updates checked never,… "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "subtle",
          "text": " "
        },
        {
          "text": "            detector: 5 mods found… "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "subtle",
          "text": " "
        },
        {
          "text": "            cache: 181 B            "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "  "
        },
        {
          "tone": "subtle",
          "text": " "
        },
        {
          "text": "            A hook that fails is l… "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "text": "                                       "
        },
        {
          "dim": true,
          "text": "│"
        }
      ],
      [
        {
          "dim": true,
          "text": "────────────────────────────────────────────────────────────────────────────────────────────────"
        }
      ],
      [
        {
          "text": "l: reload                                                            "
        },
        {
          "dim": true,
          "text": "j: jobs"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "h: keys"
        },
        {
          "text": "  "
        },
        {
          "dim": true,
          "text": "esc close"
        }
      ]
    ]
  }
]
