// Writes plugin/tests/fixtures.ts: the captured CLI runs the `claude plugin
// test` suites answer from. Plugin tests run in the hooks environment and load
// nothing from outside plugin/, so they get their own copy of the subset they
// use (test/domain/fixtures/cli-runs.ts stays the source).
//
//   node scripts/fixtures-to-plugin-tests.ts           # write the file
//   node scripts/fixtures-to-plugin-tests.ts --check   # exit 1 when the file is stale
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { runs } from '../test/domain/fixtures/cli-runs.ts'

const root = join(import.meta.dirname, '..')
const out = join(root, 'plugin', 'tests', 'fixtures.ts')

export const PICK = [
  'list',
  'validate-broken',
  'validate-plain-skill',
  'validate-quiet-bash',
  'validate-redactor',
  'validate-spawner',
  'validate-turn-band',
  'details-plain-skill',
  'details-turn-band',
  'disable-ok',
  'enable-ok',
  'uninstall-ok',
  'install-quiet-bash',
  'update-bumped',
  'update-current',
  'marketplace-update-ok',
] as const

export const generate = (): string => {
  const lines = [
    '// Generated by scripts/fixtures-to-plugin-tests.ts from test/domain/fixtures/cli-runs.ts.',
    '// Plugin tests run in the hooks environment and load nothing outside plugin/.',
    '',
    'export const RUNS = {',
  ]
  for (const key of PICK) {
    const run = runs[key]
    lines.push(
      `  ${JSON.stringify(key)}: { exitCode: ${run.exitCode}, stdout: ${JSON.stringify(run.stdout)}, stderr: ${JSON.stringify(run.stderr)} },`,
    )
  }
  lines.push('} as const', '')
  return lines.join('\n')
}

const isMain = process.argv[1] !== undefined && import.meta.filename === process.argv[1]
if (isMain) {
  const text = generate()
  if (process.argv.includes('--check')) {
    if (readFileSync(out, 'utf8') !== text) {
      console.error(
        'plugin/tests/fixtures.ts is stale: run node scripts/fixtures-to-plugin-tests.ts',
      )
      process.exit(1)
    }
  } else {
    writeFileSync(out, text)
  }
}
