// Turns the raw captures of scripts/capture-fixtures.sh into .ts fixture modules
// (`claude plugin test` cannot import .json, and vitest reads the same modules).
//
//   node scripts/fixtures-to-ts.mjs <raw dir> <out dir> <work dir> <home> <claude version>
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const [rawDir, outDir, workDir, home, version] = process.argv.slice(2)
if (!rawDir || !outDir || !workDir || !home || !version) {
  console.error('usage: fixtures-to-ts.mjs <raw> <out> <work> <home> <version>')
  process.exit(2)
}

// Machine-specific paths become stable placeholders.
const scrub = text =>
  text.split(workDir).join('/tmp/modmgr-fixtures').split(home).join('/home/user')
const read = (base, ext) => scrub(readFileSync(join(rawDir, `${base}.${ext}`), 'utf8'))

const runs = {}
for (const file of readdirSync(rawDir)
  .filter(f => f.endsWith('.argv'))
  .sort()) {
  const base = file.slice(0, -'.argv'.length)
  const name = base.replace(/^\d+-/, '')
  runs[name] = {
    argv: read(base, 'argv').trim().split('\n'),
    exitCode: Number(read(base, 'exit').trim()),
    stdout: read(base, 'stdout'),
    stderr: read(base, 'stderr'),
  }
}

// The catalogue is trimmed to ~200 representative entries: every fixture entry,
// then an even spread of each remote source kind and every relative entry, capped.
const LOCAL_MARKETPLACES = new Set(['fixtures', 'cmdmkt'])
const trimAvailable = run => {
  const parsed = JSON.parse(run.stdout)
  const kindOf = e => (typeof e.source === 'string' ? 'relative' : (e.source?.source ?? 'other'))
  const byKind = new Map()
  for (const entry of parsed.available) {
    const kind = LOCAL_MARKETPLACES.has(entry.marketplaceName) ? 'local' : kindOf(entry)
    byKind.set(kind, [...(byKind.get(kind) ?? []), entry])
  }
  const quota = { local: Infinity, relative: 20, url: 120, 'git-subdir': 60, other: 20 }
  const picked = []
  for (const [kind, entries] of byKind) {
    const take = Math.min(entries.length, quota[kind] ?? 20)
    const step = entries.length / take
    for (let i = 0; i < take; i += 1) picked.push(entries[Math.floor(i * step)])
  }
  return { ...run, stdout: `${JSON.stringify({ ...parsed, available: picked }, null, 2)}\n` }
}
if (runs['list-available']) runs['list-available'] = trimAvailable(runs['list-available'])

const header = [
  `// Generated by scripts/capture-fixtures.sh from Claude Code ${version}. Do not edit.`,
  '// Real CLI output with machine paths replaced by /tmp/modmgr-fixtures and /home/user.',
  '',
  'export type CliRun = { argv: string[]; exitCode: number; stdout: string; stderr: string }',
  '',
].join('\n')

mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'cli-runs.ts'),
  `${header}export const CLAUDE_VERSION = ${JSON.stringify(version)}\n\nexport const runs = ${JSON.stringify(runs, null, 2)} satisfies Record<string, CliRun>\n`,
)
console.log(`wrote ${Object.keys(runs).length} runs to ${join(outDir, 'cli-runs.ts')}`)
