// Generates plugin/hooks/domain/explanations.ts from the vendored d.ts: one
// plain-English line per `noun.method` on `$` and per hookable event, taken from
// the engine's own doc comments.
//
//   node scripts/gen-explanations.ts           # write the file
//   node scripts/gen-explanations.ts --check   # exit 1 when the file is stale (CI)
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const VERSION = '2.1.293'
const root = join(import.meta.dirname, '..')
const dts = join(root, 'vendor', 'claude-code-types', VERSION, 'claude-code.d.ts')
const out = join(root, 'plugin', 'hooks', 'domain', 'explanations.ts')
const MAX = 160

/** The first sentence of a doc comment, its markup removed. */
export const firstSentence = (docLines: readonly string[]): string => {
  const text: string[] = []
  for (const raw of docLines) {
    const line = raw.replace(/^\s*\/?\*+\/?\s?/, '').replace(/\*\/\s*$/, '')
    if (line.trim() === '' && text.length > 0) break
    if (line.trim().startsWith('@')) break
    if (line.trim() !== '') text.push(line.trim())
  }
  const joined = text.join(' ').replace(/`/g, '').replace(/\s+/g, ' ').trim()
  const end = joined.search(/[.;:](\s|$)/)
  const sentence = end === -1 ? joined : joined.slice(0, end)
  return sentence.length > MAX ? `${sentence.slice(0, MAX - 1).trimEnd()}…` : sentence
}

type Collected = Map<string, string>

/** Walks a block, collecting `key → doc` for members at the given indent. */
const collect = (
  lines: readonly string[],
  start: number,
  end: number,
  member: RegExp,
  keyOf: (match: RegExpExecArray, context: string | undefined) => string | undefined,
  context?: (line: string) => string | undefined,
): Collected => {
  const found: Collected = new Map()
  let doc: string[] = []
  let inDoc = false
  let current: string | undefined
  for (let i = start; i < end; i += 1) {
    const line = lines[i] ?? ''
    const trimmed = line.trim()
    if (trimmed.startsWith('/**')) {
      inDoc = !trimmed.endsWith('*/')
      doc = [line]
      continue
    }
    if (inDoc) {
      doc.push(line)
      if (trimmed.endsWith('*/')) inDoc = false
      continue
    }
    const nextContext = context?.(line)
    if (nextContext !== undefined) {
      current = nextContext
      doc = []
      continue
    }
    const match = member.exec(line)
    if (match) {
      const key = keyOf(match, current)
      const sentence = firstSentence(doc)
      if (key !== undefined && sentence !== '' && !found.has(key)) found.set(key, sentence)
    }
    if (trimmed !== '') doc = []
  }
  return found
}

const findLine = (lines: readonly string[], pattern: RegExp, from = 0): number => {
  const index = lines.findIndex((line, i) => i >= from && pattern.test(line))
  if (index === -1) throw new Error(`not found: ${pattern}`)
  return index
}

export const generate = (source: string): string => {
  const lines = source.split('\n')

  const coreStart = findLine(lines, /^ {2}export interface CoreEngineInterface \{/)
  const coreEnd = findLine(lines, /^ {2}\}/, coreStart + 1)
  const calls = collect(
    lines,
    coreStart,
    coreEnd,
    /^ {10}([a-zA-Z]+)\??[:(]/,
    (match, noun) => (noun === undefined ? undefined : `${noun}.${match[1]}`),
    line => /^ {6}([a-z]+): \{$/.exec(line)?.[1],
  )

  const eventsStart = findLine(lines, /^ {2}export type EngineEventOf = \{/)
  const eventsEnd = findLine(lines, /^ {2}\};/, eventsStart + 1)
  const events = collect(
    lines,
    eventsStart,
    eventsEnd,
    /^ {6}'([a-z]+\.[a-zA-Z.]+)':/,
    match => match[1],
  )

  const render = (map: Collected): string =>
    [...map.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
      .join('\n')

  return [
    `// Generated by scripts/gen-explanations.ts from Claude Code ${VERSION}'s d.ts. Do not edit.`,
    "// One line per `$` call and per event, in the engine's own words.",
    '',
    `export const EXPLANATIONS_VERSION = ${JSON.stringify(VERSION)}`,
    '',
    'export const CALLS: Readonly<Record<string, string>> = {',
    render(calls),
    '}',
    '',
    'export const EVENTS: Readonly<Record<string, string>> = {',
    render(events),
    '}',
    '',
  ].join('\n')
}

const isMain = process.argv[1] !== undefined && import.meta.filename === process.argv[1]
if (isMain) {
  const text = generate(readFileSync(dts, 'utf8'))
  if (process.argv.includes('--check')) {
    const current = readFileSync(out, 'utf8')
    if (current !== text) {
      console.error('domain/explanations.ts is stale: run node scripts/gen-explanations.ts')
      process.exit(1)
    }
  } else {
    writeFileSync(out, text)
    console.log(`wrote ${out}`)
  }
}
