// The landing page's terminal mock: frames drawn by the real
// ui/Pane.tsx over the fixture world the tests use, through the real actions,
// rendered to text. `site/src/data/demo.ts` must match what this draws, so the
// site can't drift from the UI; `RENDER_DEMO=1 pnpm vitest run test/demo`
// writes it again.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { DEFAULT_CONFIG } from '../../plugin/hooks/domain/config.ts'
import { createActions } from '../../plugin/hooks/services/actions.ts'
import { createRuntime } from '../../plugin/hooks/services/runtime.ts'
import { drawPane } from '../../plugin/hooks/ui/Pane.tsx'
import type { View } from '../../plugin/types/index.d.ts'
import { runs } from '../domain/fixtures/cli-runs.ts'
import { bumpTurnBand, fixtureCli } from '../services/cli-world.ts'
import { out, world } from '../services/fakes.ts'
import { ELEMENTS, installJsx, type Line, render, tidy } from './render.ts'

const COLUMNS = 96
const ROWS = 20
const DEMO = join(import.meta.dirname, '../../site/src/data/demo.ts')
const AWS = 'aws-serverless@claude-plugins-official'

type Frame = { readonly title: string; readonly caption: string; readonly lines: Line[] }

const frames = async (): Promise<Frame[]> => {
  installJsx()
  const w = world()
  fixtureCli(w.process)
    .when(['list', '--json', '--available'], out(runs['list-available'].stdout))
    .when(['marketplace', 'list'], out(runs['marketplace-list'].stdout))
  const rt = createRuntime(w.ports, DEFAULT_CONFIG, 'demo')
  w.state.values.queue = { owner: 'demo', jobs: [] }
  await rt.store.load()
  await rt.registry.refresh()
  // turn-band 0.4.0 now runs programs: the capability diff the site shows.
  bumpTurnBand(w.process)
    // Later answers win: the catalogue's own, after the bump's `list --json`.
    .when(['list', '--json', '--available'], out(runs['list-available'].stdout))
  await rt.registry.refresh()
  const act = createActions(w.ports, rt)
  const draw = async (title: string, caption: string): Promise<Frame> => {
    const tree = await drawPane(
      { el: ELEMENTS as never, surface: 'terminal', read: w.state.read, act },
      { bodyColumns: COLUMNS, bodyRows: ROWS, isFocused: true },
    )
    return { title, caption, lines: render(tree, COLUMNS).map(tidy) }
  }
  const setView = (change: Partial<View>) => {
    w.state.values.view = { ...w.state.values.view, ...change }
  }
  const shown: Frame[] = []
  // The ring on redactor: beside the list, its detail says what it can do.
  await act.focusRow('redactor@fixtures')
  shown.push(await draw('Installed', 'Every mod, what it can do at a glance, and what changed.'))
  await act.open('turn-band@fixtures')
  shown.push(
    await draw('Detail', 'An update gave turn-band a new power: said before it surprises you.'),
  )
  await act.back()
  await act.tab('discover')
  setView({ sort: 'installs' })
  await rt.catalog.show()
  shown.push(await draw('Discover', 'Every marketplace, searchable, with the mods found in it.'))
  await act.install(AWS)
  shown.push(await draw('Review', 'Nothing runs before you read what will run, and where.'))
  await act.cancel()
  await rt.dev.notice('redactor: tool.call hook failed: it threw')
  await act.tab('health')
  shown.push(await draw('Health', 'What needs you, worst first, each with a one-key fix.'))
  return shown
}

const fileOf = (shown: readonly Frame[]): string =>
  [
    '// Generated by test/demo/demo.test.ts from ui/Pane.tsx over the fixture world.',
    '// Do not edit: `RENDER_DEMO=1 pnpm vitest run test/demo` writes it again.',
    '',
    'export type Segment = {',
    '  readonly text: string',
    '  readonly tone?: string',
    '  readonly bold?: true',
    '  readonly dim?: true',
    '  readonly underline?: true',
    '  readonly ring?: true',
    '}',
    'export type Frame = {',
    '  readonly title: string',
    '  readonly caption: string',
    '  readonly lines: readonly (readonly Segment[])[]',
    '}',
    '',
    `export const COLUMNS = ${COLUMNS}`,
    '',
    `export const FRAMES: readonly Frame[] = ${JSON.stringify(shown, null, 2)}`,
    '',
  ].join('\n')

describe('the landing page’s demo', () => {
  it('matches what the dialog draws', async () => {
    const shown = await frames()
    expect(shown.map(frame => frame.title)).toEqual([
      'Installed',
      'Detail',
      'Discover',
      'Review',
      'Health',
    ])
    for (const frame of shown) {
      for (const line of frame.lines) {
        expect(line.reduce((sum, seg) => sum + [...seg.text].length, 0)).toBeLessThanOrEqual(
          COLUMNS,
        )
      }
    }
    const text = fileOf(shown)
    if (process.env.RENDER_DEMO === '1') writeFileSync(DEMO, text)
    expect(readFileSync(DEMO, 'utf8')).toBe(text)
  })
})
